language: workflow

tools:
  jdk:
    - 1.8.0_91-b14
  maven:
    - 3.3.9

flows:
  master:
  - (on master, name mvn -f io.takari.modello.editor.mapping install && mvn package) mvn -f io.takari.modello.editor.mapping install && mvn package -B 
  pr:
  - call: master
